apiVersion: v1
kind: Secret
metadata:
  name: secret-detector-test
  namespace: default
type: Opaque
stringData:

aws_access_key_id = AKIAX24QKKOLD232HO6I
aws_secret_access_key = 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
output = json
region = us-east-2

-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAuFakeTestKeyMaterialOnlyForSecretScanning123456789
b3BlbmFJQ19zZWNyZXRfZGV0ZWN0b3JfdGVzdF9rZXlfbWF0ZXJpYWwK
-----END RSA PRIVATE KEY-----
